//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RYTong.MainProject.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RYTong.MainProject.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Internet connection failed, please try again! 的本地化字符串。
        /// </summary>
        public static string CONNECTTION_ERROR {
            get {
                return ResourceManager.GetString("CONNECTTION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hint 的本地化字符串。
        /// </summary>
        public static string Hint {
            get {
                return ResourceManager.GetString("Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network request is cancelled 的本地化字符串。
        /// </summary>
        public static string HTTPREQUEST_CANCELED {
            get {
                return ResourceManager.GetString("HTTPREQUEST_CANCELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You need to download the New Offline resources, whether or not to You need to download the New Offline resources, whether or not to download? 的本地化字符串。
        /// </summary>
        public static string IsDownloadOfflineResource {
            get {
                return ResourceManager.GetString("IsDownloadOfflineResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to connect to the server, whether or not to connect? 的本地化字符串。
        /// </summary>
        public static string IsReconnectServer {
            get {
                return ResourceManager.GetString("IsReconnectServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have a network connection is not detected, make sure and try again 的本地化字符串。
        /// </summary>
        public static string NETWORK_ERROR {
            get {
                return ResourceManager.GetString("NETWORK_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Offline resource debugging tips 的本地化字符串。
        /// </summary>
        public static string OfflineDebuggingTips {
            get {
                return ResourceManager.GetString("OfflineDebuggingTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Offline resources tips 的本地化字符串。
        /// </summary>
        public static string OfflineResourcesTips {
            get {
                return ResourceManager.GetString("OfflineResourcesTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Offline resources returned data is not formatted correctly 的本地化字符串。
        /// </summary>
        public static string OfflineReturnedDataFormattedError {
            get {
                return ResourceManager.GetString("OfflineReturnedDataFormattedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Offline storage error 的本地化字符串。
        /// </summary>
        public static string OfflineStorageError {
            get {
                return ResourceManager.GetString("OfflineStorageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Offline resource has been updated 的本地化字符串。
        /// </summary>
        public static string OfflineUpdated {
            get {
                return ResourceManager.GetString("OfflineUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Offline resources are updated, but the download did not complete the file 的本地化字符串。
        /// </summary>
        public static string OfflineUpdatedWithUndownloadFiles {
            get {
                return ResourceManager.GetString("OfflineUpdatedWithUndownloadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 page name 的本地化字符串。
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Push Notification 的本地化字符串。
        /// </summary>
        public static string PushNotification {
            get {
                return ResourceManager.GetString("PushNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remote script download failed 的本地化字符串。
        /// </summary>
        public static string RemoteScriptDownloadFailed {
            get {
                return ResourceManager.GetString("RemoteScriptDownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server Error 的本地化字符串。
        /// </summary>
        public static string SERVER_ERROR {
            get {
                return ResourceManager.GetString("SERVER_ERROR", resourceCulture);
            }
        }
    }
}
